# Generated by Django 3.2.3 on 2021-06-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20210616_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=1000, verbose_name='Yorum'),
        ),
    ]
