# Generated by Django 3.2.3 on 2021-06-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_comment_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ad'),
        ),
    ]
